apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-group2-backend
  labels:
    app: devops-group2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-group2-backend
  template:
    metadata:
      labels:
        app: devops-group2-backend
    spec:
      containers:
        - name: devops-group2-backend
          image: dmuchoki/client-image:2.0.0
          tty: true
          ports:
            - containerPort: 3000