apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-group2-backend
  labels:
    app: devops-group2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-group2-backend
  template:
    metadata:
      labels:
        app: devops-group2-backend
    spec:
      containers:
        - name: devops-group2-backend
          image: dmuchoki/backend-image:1.0.0
          ports:
            - containerPort: 5000

 

  env:
    name: MONGODB_URI
    valueFrom:
      secretKeyRef: 
        name: devops-group2-backend-secrets
        key: MONGODB_URI