apiVersion: apps/v1
kind: Deploment
metadata:
  name: devops-group2-database-deployment
spec:
  selector:
    app: devops-group2-database-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-group2-database-deployment
    spec:
      containers:
        name: devops-group2-database-deployment
        image: mongo
        ports:
          - containerport: 27017
        env:
    name: MONGO_INITDB_ROOT_USERNAME
    valueFrom:
      secretKeyRef: 
        name: devops-group2-secrets
        key: MONGO_INITDB_ROOT_USERNAME

    name: MONGO_INITDB_ROOT_PASSWORD
    valueFrom:
      secretKeyRef: 
        name: devops-group2-secrets
        key: MONGO_INITDB_ROOT_PASSWORD
 